name: Triggers Workflow
 
on: 
 push:
 pull_request:
 workflow_dispatch:
 schedule:
    - cron: "*/8 * * * *"
jobs:
 
 echo-print:
  runs-on: ubuntu-latest
  steps:
      - run: echo "Triggers workflow"
